services:
  development:
    build:
      context: .
      dockerfile: Dockerfile/development.Dockerfile
    ports:
      - 8888:8888
    command:
      - bash
      - -c
      - |
        pip install -e .[dev]
        pre-commit install
        jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --port 8888 --NotebookApp.token='' --NotebookApp.password=''
    volumes:
      - .:/app
  dagster-data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile/dagster.Dockerfile
    environment:
      - DAGSTER_HOME=/app/dagster_storage
    command:
      - bash
      - -c
      - |
        pip install -e .
        dagster dev -h 0.0.0.0 -p 3000
    volumes:
      - ./dagster_storage/:/app/dagster_storage/
      - ./data_engineering/:/app/data_engineering/
      - ./sg_taxi_data/:/app/sg_taxi_data/
    ports:
      - 3000:3000
  minio-datalake:
    image: bitnami/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - "./datalake:/bitnami/minio/data"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_DEFAULT_BUCKETS: "raw,bronze,silver,gold"
volumes:
  dagster_storage:
  data_engineering:
  sg_taxi_data:
  datalake:
