[tool.isort]
profile = 'black'

[tool.pylint.format]
max-line-length = 120

[tool.black]
line-length = 120

[tool.pylint]
init-hook = '''
import sys
sys.path.append('./dagster_service')
sys.path.append('./webapp_service')
'''
